#!/bin/bash

java -jar ../out/artifacts/xrules.jar < ./rules-tests/1-in.json > results.temp
diff results.temp ./rules-tests/1-out.json

rm results.temp

java -jar ../out/artifacts/xrules.jar < ./rules-tests/2-in.json > results.temp
diff results.temp ./rules-tests/2-out.json

rm results.temp

java -jar ../out/artifacts/xrules.jar < ./rules-tests/3-in.json > results.temp
diff results.temp ./rules-tests/3-out.json

rm results.temp

java -jar ../out/artifacts/xrules.jar < ./rules-tests/4-in.json > results.temp
diff results.temp ./rules-tests/4-out.json

rm results.temp

java -jar ../out/artifacts/xrules.jar < ./rules-tests/5-in.json > results.temp
diff results.temp ./rules-tests/5-out.json

rm results.temp