#!/bin/bash

java -jar ../out/artifacts/xstrategy.jar < ./strategy-tests/1-in.json > results.temp
diff results.temp ./strategy-tests/1-out.json

rm results.temp

java -jar ../out/artifacts/xstrategy.jar < ./strategy-tests/2-in.json > results.temp
diff results.temp ./strategy-tests/2-out.json

rm results.temp

java -jar ../out/artifacts/xstrategy.jar < ./strategy-tests/3-in.json > results.temp
diff results.temp ./strategy-tests/3-out.json

rm results.temp

java -jar ../out/artifacts/xstrategy.jar < ./strategy-tests/4-in.json > results.temp
diff results.temp ./strategy-tests/4-out.json

rm results.temp

java -jar ../out/artifacts/xstrategy.jar < ./strategy-tests/5-in.json > results.temp
diff results.temp ./strategy-tests/5-out.json

rm results.temp
